/**
 * Map for services to friendly names.
 *
 * When importing resources, the resource value can be the short-name
 * e.g Importing an SNS resource would result in `sns`. This map is used on the frontend
 * to render nice names for the services.
 */

const services = {
  lambda: "AWS Lambda",
  "step-function": "AWS Step Functions",
  sqs: "Amazon SQS",
  sns: "Amazon SNS",
  dynamodb: "Amazon DynamoDB",
  ec2: "Amazon EC2",
  s3: "Amazon S3",
  rds: "Amazon RDS",
  ecs: "Amazon ECS",
  ecr: "Amazon ECR",
  iam: "AWS Identity and Access Management",
  cloudfront: "Amazon CloudFront",
  apigateway: "Amazon API Gateway",
  ssm: "AWS Systems Manager",
  cloudwatch: "Amazon CloudWatch",
  cognito: "Amazon Cognito",
  kinesis: "Amazon Kinesis",
  redshift: "Amazon Redshift",
  elb: "Elastic Load Balancing",
  vpc: "Amazon VPC",
  route53: "Amazon Route 53",
  glue: "AWS Glue",
  athena: "Amazon Athena",
  sagemaker: "Amazon SageMaker",
  secretsmanager: "AWS Secrets Manager",
  kms: "AWS Key Management Service",
  efs: "Amazon Elastic File System",
  ebs: "Amazon Elastic Block Store",
  fargate: "AWS Fargate",
  emr: "Amazon EMR",
  elasticache: "Amazon ElastiCache",
  lightsail: "Amazon Lightsail",
  docdb: "Amazon DocumentDB",
  neptune: "Amazon Neptune",
  mq: "Amazon MQ",
  kendra: "Amazon Kendra",
  comprehend: "Amazon Comprehend",
  transcribe: "Amazon Transcribe",
  rekognition: "Amazon Rekognition",
  lex: "Amazon Lex",
  polly: "Amazon Polly",
  textract: "Amazon Textract",
  forecast: "Amazon Forecast",
  personalize: "Amazon Personalize",
  qldb: "Amazon Quantum Ledger Database",
  managedblockchain: "Amazon Managed Blockchain",
  codecommit: "AWS CodeCommit",
  codebuild: "AWS CodeBuild",
  codepipeline: "AWS CodePipeline",
  codedeploy: "AWS CodeDeploy",
  codeartifact: "AWS CodeArtifact",
  codestar: "AWS CodeStar",
  xray: "AWS X-Ray",
  mediapackage: "AWS Elemental MediaPackage",
  medialive: "AWS Elemental MediaLive",
  mediastore: "AWS Elemental MediaStore",
  mediatailor: "AWS Elemental MediaTailor",
  mediainfo: "AWS Elemental MediaInfo",
  datapipeline: "AWS Data Pipeline",
  dms: "AWS Database Migration Service",
  sms: "AWS Server Migration Service",
  msckafka: "Amazon Managed Streaming for Apache Kafka",
  pinpoint: "Amazon Pinpoint",
  ses: "Amazon Simple Email Service",
  connect: "Amazon Connect",
  chime: "Amazon Chime",
  quicksight: "Amazon QuickSight",
  macie: "Amazon Macie",
  guardduty: "Amazon GuardDuty",
  inspector: "Amazon Inspector",
  waf: "AWS WAF",
  shield: "AWS Shield",
  honeycode: "Amazon Honeycode",
  timestream: "Amazon Timestream",
  appflow: "Amazon AppFlow",
  apprunner: "AWS App Runner",
  lookoutmetrics: "Amazon Lookout for Metrics",
  lookoutvision: "Amazon Lookout for Vision",
  monitron: "Amazon Monitron",
  panther: "AWS Panorama",
  sso: "AWS Single Sign-On",
  directoryservice: "AWS Directory Service",
  workspaces: "Amazon WorkSpaces",
  workdocs: "Amazon WorkDocs",
  workmail: "Amazon WorkMail",
  worklink: "Amazon WorkLink",
  appstream: "Amazon AppStream 2.0",
  iotcore: "AWS IoT Core",
  iotanalytics: "AWS IoT Analytics",
  iotdevice: "AWS IoT Device Management",
  iotgreengrass: "AWS IoT Greengrass",
  iotsitewise: "AWS IoT SiteWise",
  iotthingsgraph: "AWS IoT Things Graph",
  groundstation: "AWS Ground Station",
  outposts: "AWS Outposts",
  snowball: "AWS Snowball",
  snowmobile: "AWS Snowmobile",
  wavelength: "AWS Wavelength",
  robomaker: "AWS RoboMaker",
  deepracer: "AWS DeepRacer",
  deeplens: "AWS DeepLens",
  deepcomposer: "AWS DeepComposer",
  braket: "Amazon Braket",
  healthlake: "Amazon HealthLake",
  ivs: "Amazon Interactive Video Service",
  lakeformation: "AWS Lake Formation",
  msk: "Amazon Managed Streaming for Kafka",
  codeguru: "Amazon CodeGuru",
  frauddetector: "Amazon Fraud Detector",
  detective: "Amazon Detective",
  devopsguru: "Amazon DevOps Guru",
  lookoutforequipment: "Amazon Lookout for Equipment",
  lookoutforvision: "Amazon Lookout for Vision",
  elasticbeanstalk: "AWS Elastic Beanstalk",
  fms: "AWS Firewall Manager",
  controltower: "AWS Control Tower",
  managedgrafana: "Amazon Managed Grafana",
  prometheus: "Amazon Managed Service for Prometheus",
  signers: "AWS Signer",
  wellarchitected: "AWS Well-Architected Tool",
  amplify: "AWS Amplify",
  appmesh: "AWS App Mesh",
  appconfig: "AWS AppConfig",
  backup: "AWS Backup",
  batch: "AWS Batch",
  cloud9: "AWS Cloud9",
  cloudformation: "AWS CloudFormation",
  cloudhsm: "AWS CloudHSM",
  cloudsearch: "Amazon CloudSearch",
  cloudshell: "AWS CloudShell",
  codestarconnections: "AWS CodeStar Connections",
  codestarnotifications: "AWS CodeStar Notifications",
  computeoptimizer: "AWS Compute Optimizer",
  config: "AWS Config",
  costexplorer: "AWS Cost Explorer",
  customerprofiles: "Amazon Connect Customer Profiles",
  databrew: "AWS Glue DataBrew",
  datasync: "AWS DataSync",
  directconnect: "AWS Direct Connect",
  dlm: "Amazon Data Lifecycle Manager",
  documentdb: "Amazon DocumentDB",
  ds: "AWS Directory Service",
  dynamodbaccelerator: "Amazon DynamoDB Accelerator (DAX)",
  ec2autoscaling: "Amazon EC2 Auto Scaling",
  ec2imagebuilder: "EC2 Image Builder",
  elasticfilesystem: "Amazon Elastic File System",
  elasticinference: "Amazon Elastic Inference",
  elasticloadbalancing: "Elastic Load Balancing",
  elastictranscoder: "Amazon Elastic Transcoder",
  elasticsearchservice: "Amazon Elasticsearch Service",
  elementalmediaconnect: "AWS Elemental MediaConnect",
  elementalmediaconvert: "AWS Elemental MediaConvert",
  elementalmediapackage: "AWS Elemental MediaPackage",
  elementalmediapackagevod: "AWS Elemental MediaPackage VoD",
  elementalmediastore: "AWS Elemental MediaStore",
  elementalmediatailor: "AWS Elemental MediaTailor",
  eventbridge: "Amazon EventBridge",
  events: "Amazon EventBridge",
  firehose: "Amazon Kinesis Firehose",
  fsx: "Amazon FSx",
  gamelift: "Amazon GameLift",
};

export default services;
